import * as React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faAddressCard, faAngleDown, faAngleUp, faBolt, faBoxes, faChartLine, faChartPie, faCheck, faCog, faCogs, faEdit, faExclamationCircle, faHandHoldingUsd, faImages, faInfoCircle, faLightbulb, faLink, faListUl, faLock, faMagic, faMoon, faPencilAlt, faPiggyBank, faPlayCircle, faPlus, faSearch, faSignInAlt, faSignOutAlt, faSkull, faStar, faTable, faTachometerAlt, faTextHeight, faTimes, faTint, faTrashAlt, faUser, faUserPlus, faVolleyballBall } from '@fortawesome/free-solid-svg-icons';
import { IconProp, library } from '@fortawesome/fontawesome-svg-core';

library.add(faAddressCard, faAngleUp, faAngleDown, faBolt, faBoxes, faChartLine, faChartPie, faCheck, faCog, faCogs, faEdit, faExclamationCircle, faHandHoldingUsd, faImages, faInfoCircle, faLightbulb, faLink, faListUl, faLock, faMagic, faMoon, faPencilAlt, faPiggyBank, faPlayCircle, faPlus, faSearch, faSignInAlt, faSignOutAlt, faSkull, faStar, faTable, faTachometerAlt, faTextHeight, faTimes, faTint, faTrashAlt, faUser, faUserPlus, faVolleyballBall);

const Icon = (icon: IconProp) => (props?: { className?: string; }) => <span className={`icon ${props?.className}`}><FontAwesomeIcon icon={icon} /></span>;
export const AddressCardIcon = Icon('address-card');
export const AngleDownIcon = Icon('angle-down');
export const AngleUpIcon = Icon('angle-up');
export const BoltIcon = Icon('bolt');
export const BoxesIcon = Icon('boxes');
export const ChartLineIcon = Icon('chart-line');
export const ChartPieIcon = Icon('chart-pie');
export const CheckIcon = Icon('check');
export const CogIcon = Icon('cog');
export const CogsIcon = Icon('cogs');
export const ExclamationCircleIcon = Icon('exclamation-circle');
export const HandHoldingUsdIcon = Icon('hand-holding-usd');
export const ImagesIcon = Icon('images');
export const InfoCircle = Icon('info-circle');
export const LightbulbIcon = Icon('lightbulb');
export const LinkIcon = Icon('link');
export const ListUlIcon = Icon('list-ul');
export const LockIcon = Icon('lock');
export const MagicIcon = Icon('magic');
export const MoonIcon = Icon('moon');
export const PencilAltIcon = Icon('pencil-alt');
export const PiggyBankIcon = Icon('piggy-bank');
export const PlayCircleIcon = Icon('play-circle');
export const PlusIcon = Icon('plus');
export const SearchIcon = Icon('search');
export const SignInAltIcon = Icon('sign-in-alt');
export const SignOutAltIcon = Icon('sign-out-alt');
export const SkullIcon = Icon('skull');
export const StarIcon = Icon('star');
export const TableIcon = Icon('table');
export const TachometerAltIcon = Icon('tachometer-alt');
export const TextHeightIcon = Icon('text-height');
export const TimesIcon = Icon('times');
export const TintIcon = Icon('tint');
export const TrashAltIcon = Icon('trash-alt');
export const UserIcon = Icon('user');
export const UserPlusIcon = Icon('user-plus');
export const VolleyBallIcon = Icon('volleyball-ball');

const Flag = (countryCode: string) => (props?: { className?: string; }) => <i className={`flag-icon flag-icon-${countryCode}`} title={countryCode} id={countryCode}></i>;
export const TwFlag = Flag('tw');
export const UsFlag = Flag('us');
